# First, you need to create a configuration file, ".env", in the same directory
# as this file, "docker-compose.yml".  Add the following environment variables
# to this configuration file.
#
#SITENAME=unique id
#
 version: "3.0"

 services:
    probetest:
        network_mode: host
        image: thetorproject/probetest:latest
        container_name: probe
        environment:
          # Exit with an error message if required vars are unset or empty.
          - SITENAME=${SITENAME:?Env var SITENAME is not set.}
          - UID=${UID:?Env var UID is not set.}
        restart: unless-stopped
        volumes:
          - ./log:/bridgetest/log
